# Generated by Django 4.2.1 on 2023-08-31 05:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
        ('stock', '0002_stock_marketprice_stock_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('salt', models.CharField(max_length=10)),
                ('legal_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('crypto', models.ManyToManyField(related_name='CryptoQuantity', to='crypto.crypto')),
                ('stocks', models.ManyToManyField(related_name='StockQuantity', to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField()),
                ('shares', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField()),
                ('shares', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
