# Generated by Django 4.2.1 on 2023-08-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
        ('stock', '0003_alter_stock_marketprice'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoquantity',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockquantity',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='crypto',
            field=models.ManyToManyField(blank=True, related_name='CryptoQuantity', to='crypto.crypto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='legal_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='StockQuantity', to='stock.stock'),
        ),
    ]
