# Generated by Django 4.2.1 on 2023-08-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='marketPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
