# Generated by Django 4.2.1 on 2023-08-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_marketprice_stock_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='marketPrice',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
